---
version: "3.8"
services:
  movies:
    image: sudesh1209/paymovies:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
    recharge:
        image: sudesh1209/payrecharge:latest
        ports:
          - 83:80
        deploy:
          replicas: 3
        dth:
          image: sudesh1209/paydth:latest
          ports:
            - 84:80
          deploy:
            replicas: 3
